config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'cats#index'
  resources :cats

  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post '/approve', to: 'cat_rental_requests#approve', as: 'approve'
      post '/deny', to: 'cat_rental_requests#deny', as: 'deny'
    end
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]
end

app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS =  %w(White Black Brown Blue Yellow Green Red Pink)

    validates :birth_date, :color, :name, :sex, :description, presence: true
    validates :sex, inclusion: { in: %w(M F) }
    validates :color, inclusion: CAT_COLORS

    has_many :cat_rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    belongs_to :owner,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :User

    def age
        time_ago_in_words(self.birth_date)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

    before_action :require_login, only: [:new, :create, :edit, :update]

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        @rental_requests = @cat.cat_rental_requests.order(:start_date)

        if @cat
            render :show
        else
            render json: "Cat not found"
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        # @cat.user_id = current_user.id
        @cat.owner = current_user

        if @cat.save
            redirect_to cats_url
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :new
        end
    end

    def edit
        @cat = current_user.cats.find(id: params[:id])
        
        render :edit
    end

    def update
        @cat = current_user.cats.find(id: params[:id])

        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            flash.now[:errors] = @cat.errors.full_messages
            render :edit
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
    end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% if type === "Edit"%>
    <% action = cat_url(cat) %>
    <% submit = "Update a cat"%>
<% else%>
    <% action = cats_url %>
    <% submit = "Create a cat"%>
<% end%>


<form action="<%= action %>" method="post">
    <% if type === "Edit"%>
        <input type="hidden" name="_method" value="patch">
    <% end%>
    <label for="name">Name:</label>
    <input type="text" name="cat[name]" id="name" value=<%= @cat.name %>>

    <br>

    <label>Sex</label>
    <input type="radio" name="cat[sex]" id="sex_male" value="M" <%= @cat.sex === "M" ? "checked" : ""%>>
    <label for="sex_male">Male</label>

    <input type="radio" name="cat[sex]" id="sex_female" value="F" <%= @cat.sex === "F" ? "checked" : ""%>>
    <label for="sex_female">Female</label>

    <br>

    <label for="color">Color:</label>
    <select id="color" name="cat[color]">
        <option value="" disabled>--Select a color--</option>
        <% Cat::CAT_COLORS.each do |color| %>
            <option 
            <%= @cat.color == color ? "selected" : "" %>
            value="<%= color %>"><%= color %></option>
        <% end%>
    </select>

    <br>

    <label for="date">Birth Date:</label>
    <input type="date" name="cat[birth_date]" id="date" value=<%= @cat.birth_date %>>
    
    <br>

    <label for="description">Description:</label>
    <textarea name="cat[description]" id="description"><%= @cat.description %></textarea>

    <br>

    <input type="submit" value=<%= submit %>>
</form>

<a href="<%= cats_url %>">Home Page</a>

app/views/cats/edit.html.erb
<h1>Edit a Cat</h1>

<%= render 'form', cat: @cat, type: "Edit"%>

app/views/cats/index.html.erb
<% if current_user %>
    <p>Welcome: <%= current_user.username %></p>
<% end%>

<h1>All Our Cats</h1>

<% if !current_user %>
    <a href="<%= new_user_url %>">Sign Up</a>
    <br>
    <a href="<%= new_session_url %>">Log In</a>
    <br>
<% end%>
<a href="<%= new_cat_url %>">+Add Cat</a>
<ul>
    <% @cats.each do |cat|%>
        <li><a href="/cats/<%= cat.id %>"><%= cat.name %></a></li>
    <% end%>
</ul>

app/views/cats/new.html.erb
<h1>Create a new Cat</h1>

<%= render 'form', cat: @cat, type: "New"%>

app/views/cats/show.html.erb
<h1><%= @cat.name %>'s Data</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Sex</th>
        <th>Age</th>
        <th>Color</th>
        <th>Description</th>
    </tr>
    
    <tr>
        <td><%= @cat.name %></td>
        <td><%= @cat.sex %></td>
        <td><%= @cat.age %></td>
        <td><%= @cat.color %></td>
        <td><%= @cat.description %></td>
    </tr>
</table>

<h1>Rental Requests</h1>
<% if @rental_requests.length > 0 %>
<table>
    <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Approve or Deny</th>
        <th>Requester Name</th>
    </tr>
    
    <% @rental_requests.each do |request| %>
        <tr>
            <td><%= request.start_date %></td>
            <td><%= request.end_date %></td>
            <td><%= request.status %></td>
            <% if request.status === "PENDING" && request.cat.user_id === current_user.id%>
            <td>
                <form action="<%= approve_cat_rental_request_url(request) %>" method="post">
                    <input type="submit" value="Approve">
                </form>

                <form action="<%= deny_cat_rental_request_url(request) %>" method="post">
                    <input type="submit" value="Deny">
                </form>
            </td>
            <% else %>
                <td>Waiting for approval</td>
            <% end%>
            <td><%= request.requester.username %></td>
            
        </tr>
    <% end %>
</table>

<% else %>
    <p>No requests yet!!!</p>
<% end%>

<a href="<%= edit_cat_url(@cat) %>">Edit Cat</a>
<br>
<a href="<%= cats_url %>">Home Page</a>
<br>
<a href="<%= new_cat_rental_request_url %>">Make New Request</a>